---
apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-config
  namespace: kube-system
  labels:
    k8s-app: filebeat
data:
  filebeat.yml: |-
    setup.template.settings:
      index.mapping.total_fields.limit: 10000

    filebeat.autodiscover:
     providers:
       - type: kubernetes
         host: ${NODE_NAME}
         hints.enabled: true

    processors:
      - add_cloud_metadata:
      - add_host_metadata:
      - add_docker_metadata:
      - add_kubernetes_metadata:
      - drop_event:
          when:
            or:
            - contains:
                message: "OpenAPI AggregationController: Processing item k8s_internal_local_delegation_chain"
            - and:
              - equals:
                  kubernetes.container.name: "metricbeat"
              - contains:
                  message: "INFO"
              - contains:
                  message: "Non-zero metrics in the last"
            - and:
              - equals:
                  kubernetes.container.name: "packetbeat"
              - contains:
                  message: "INFO"
              - contains:
                  message: "Non-zero metrics in the last"
            - contains:
                message: "get services heapster"
            - contains:
                kubernetes.container.name: "kube-addon-manager"
            - contains:
                kubernetes.container.name: "dashboard-metrics-scraper"

    cloud.id: ${ELASTIC_CLOUD_ID}
    cloud.auth: ${ELASTIC_CLOUD_AUTH}

    # This part is only required with ECK-based Elastic cluster
    output.elasticsearch:
      hosts: ['${ELASTICSEARCH_HOST:elasticsearch}:${ELASTICSEARCH_PORT:9200}']
      username: ${ELASTICSEARCH_USERNAME}
      password: ${ELASTICSEARCH_PASSWORD}
      ssl.verification_mode: none
    setup.kibana:
      host: ${KIBANA_HOST}
      ssl.verification_mode: none

    logging.metrics.enabled: false
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: filebeat
  namespace: kube-system
  labels:
    k8s-app: filebeat
spec:
  selector:
    matchLabels:
      k8s-app: filebeat
  template:
    metadata:
      labels:
        k8s-app: filebeat
    spec:
      serviceAccountName: filebeat
      terminationGracePeriodSeconds: 30
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
      - name: filebeat
        image: docker.elastic.co/beats/filebeat:7.7.0
        args: [
          "-c", "/etc/filebeat.yml",
          "-e",
        ]
        env:

        # This section is for connecting to Elastic cluster running through ECK
        #  in the default namespace. Uncomment this section and comment out the
        # init section with ELASTIC_CLOUD_ID and ELASTIC_CLOUD_AUTH variables
        - name: KIBANA_HOST
          value: "https://quickstart-kb-http.default.svc.cluster.local"
        - name: ELASTICSEARCH_HOST
          value: "https://quickstart-es-http.default.svc.cluster.local"
        - name: ELASTICSEARCH_PORT
          value: "9200"
        - name: ELASTICSEARCH_USERNAME
          value: elastic
        - name: ELASTICSEARCH_PASSWORD
          valueFrom:
            secretKeyRef:
              name: eck-secret
              key: elastic-password
        # End of ECK cluster connectivity

        # # This section is for connecting to Elastic Cloud cluster using
        # #  ELASTIC_CLOUD_ID and ELASTIC_CLOUD_AUTH defined through secrets
        # - name: ELASTIC_CLOUD_ID
        #   valueFrom:
        #     secretKeyRef:
        #       name: cloud-secret
        #       key: cloud-id
        # - name: ELASTIC_CLOUD_AUTH
        #   valueFrom:
        #     secretKeyRef:
        #       name: cloud-secret
        #       key: cloud-auth
        # # End of Elastic Cloud connectivity section

        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        securityContext:
          runAsUser: 0
          # If using Red Hat OpenShift uncomment this:
          # privileged: true
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 100Mi
        volumeMounts:
        - name: config
          mountPath: /etc/filebeat.yml
          readOnly: true
          subPath: filebeat.yml
        - name: data
          mountPath: /usr/share/filebeat/data
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
        - name: varlog
          mountPath: /var/log
          readOnly: true
        - name: dockersock
          mountPath: "/var/run/docker.sock"
      volumes:
      - name: config
        configMap:
          defaultMode: 0600
          name: filebeat-config
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      - name: varlog
        hostPath:
          path: /var/log
      # data folder stores a registry of read status for all files, so we don't send everything again on a Filebeat pod restart
      - name: data
        hostPath:
          path: /var/lib/filebeat-data
          type: DirectoryOrCreate
      - name: dockersock
        hostPath:
          path: /var/run/docker.sock
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: filebeat
subjects:
- kind: ServiceAccount
  name: filebeat
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: filebeat
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: filebeat
  labels:
    k8s-app: filebeat
rules:
- apiGroups: [""] # "" indicates the core API group
  resources:
  - namespaces
  - pods
  verbs:
  - get
  - watch
  - list
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: filebeat
  namespace: kube-system
  labels:
    k8s-app: filebeat
---
