#!/bin/sh -xvf

# Here go the values
cloud_id = ...
cloud_auth = ...
api_url = ...
api_token = ...

kubectl create secret generic cloud-secret --namespace=kube-system --from-literal=cloud-id=$cloud_id
kubectl create secret generic cloud-secret --namespace=kube-system --from-literal=cloud-auth=$cloud_auth
kubectl create secret generic apm-secret --from-literal=apm-url=$apm_url
kubectl create secret generic apm-secret --from-literal=apm-token=$apm_token
